[tool.poetry]
name = "advent-of-code"
version = "0.1.0-2020"
description = ""
authors = ["Inigo Moreno <ignigomoreno@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
